name: mmseg
channels:
  - defaults
dependencies:
  - anyio=4.2.0=py38haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py38haa95532_0
  - attrs=24.2.0=py38haa95532_0
  - babel=2.11.0=py38haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py38haa95532_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2025.7.15=haa95532_0
  - cffi=1.17.1=py38h827c3e9_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.2.1=py38haa95532_0
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - h11=0.14.0=py38haa95532_0
  - httpcore=1.0.2=py38haa95532_0
  - httpx=0.27.0=py38haa95532_0
  - icu=73.1=h6c2663c_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38haa95532_0
  - ipykernel=6.29.5=py38haa95532_0
  - ipython=8.12.2=py38haa95532_0
  - ipywidgets=8.1.2=py38haa95532_0
  - jedi=0.19.1=py38haa95532_0
  - jinja2=3.1.4=py38haa95532_0
  - jpeg=9e=h827c3e9_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.23.0=py38haa95532_0
  - jsonschema-specifications=2023.7.1=py38haa95532_0
  - jupyter=1.0.0=py38haa95532_9
  - jupyter-lsp=2.2.0=py38haa95532_0
  - jupyter_client=8.6.0=py38haa95532_0
  - jupyter_console=6.6.3=py38haa95532_0
  - jupyter_core=5.7.2=py38haa95532_0
  - jupyter_events=0.10.0=py38haa95532_0
  - jupyter_server=2.14.1=py38haa95532_0
  - jupyter_server_terminals=0.4.4=py38haa95532_1
  - jupyterlab=4.2.5=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py38haa95532_0
  - jupyterlab_widgets=3.0.10=py38haa95532_0
  - krb5=1.20.1=h5b6d351_0
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libffi=3.4.4=hd77b12b_1
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libsodium=1.0.18=h62dcd97_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mistune=2.0.4=py38haa95532_0
  - nbclient=0.8.0=py38haa95532_0
  - nbconvert=7.16.4=py38haa95532_0
  - nbformat=5.10.4=py38haa95532_0
  - nest-asyncio=1.6.0=py38haa95532_0
  - notebook=7.2.2=py38haa95532_1
  - notebook-shim=0.2.3=py38haa95532_0
  - openssl=3.0.17=h35632f6_0
  - overrides=7.4.0=py38haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py38haa95532_0
  - pkgutil-resolve-name=1.3.10=py38haa95532_1
  - ply=3.11=py38_0
  - prometheus_client=0.14.1=py38haa95532_0
  - prompt-toolkit=3.0.43=py38haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0post0=py38haa95532_2
  - python-fastjsonschema=2.16.2=py38haa95532_0
  - python-json-logger=2.0.7=py38haa95532_0
  - pytz=2024.1=py38haa95532_0
  - pywin32=305=py38h2bbff1b_0
  - pywinpty=2.0.10=py38h5da7b33_0
  - pyyaml=6.0.2=py38h827c3e9_0
  - pyzmq=25.1.2=py38hd77b12b_0
  - qt-main=5.15.2=h19c9488_12
  - qtconsole=5.6.0=py38haa95532_0
  - qtpy=2.4.1=py38haa95532_0
  - referencing=0.30.2=py38haa95532_0
  - requests=2.32.3=py38haa95532_0
  - rfc3339-validator=0.1.4=py38haa95532_0
  - rfc3986-validator=0.1.1=py38haa95532_0
  - rpds-py=0.10.6=py38h062c2fa_0
  - send2trash=1.8.2=py38haa95532_0
  - setuptools=75.1.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - sniffio=1.3.0=py38haa95532_0
  - soupsieve=2.5=py38haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py38haa95532_0
  - tinycss2=1.2.1=py38haa95532_0
  - tornado=6.4.1=py38h827c3e9_0
  - traitlets=5.14.3=py38haa95532_0
  - typing_extensions=4.11.0=py38haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.2.3=py38haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - webencodings=0.5.1=py38_1
  - websocket-client=1.8.0=py38haa95532_0
  - wheel=0.44.0=py38haa95532_0
  - widgetsnbextension=4.0.10=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.20.2=py38haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - absl-py==2.2.2
      - addict==2.4.0
      - annotated-types==0.7.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.2
      - fonttools==4.57.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.39.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.4
      - mdurl==0.1.2
      - mmcv==2.0.0
      - mmengine==0.10.7
      - numpy==1.24.4
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pillow==9.5.0
      - platformdirs==4.3.6
      - prettytable==3.11.0
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.1.4
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - scikit-learn==1.3.2
      - scipy==1.9.3
      - sentry-sdk==2.27.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tomli==2.2.1
      - torch==1.13.1+cu117
      - torchvision==0.14.1+cu117
      - typing-extensions==4.13.2
      - wandb==0.19.10
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - yapf==0.43.0
prefix: C:\dlcv\envs\mmseg
